### PR TITLE
Feature/authentication

### PR DESCRIPTION
**Pull request by CR4ZED**
This PR has the following changes:
1. Implemented authentication signin and signup routes with dedicated auth pages
2. Added support for Google and GitHub OAuth providers
3. Created a responsive container for better layout and design
4. Added user logged in check in the navbar

### CODE REVIEW

**Review by CR4ZED — COMMENTED** [review]
Please suggest changes for @ts-ignore comments, I am not sure how to fix those

**Comment by LKPcode** [comment]
I believe we need to set some environment variables:
```
GITHUB_ID=...
GITHUB_SECRET=...

GOOGLE_ID=...
GOOGLE_SECRET=...
```
Are these correct? 
Are there any other variables we need to define?

**Comment by CR4ZED** [comment]
> I believe we need to set some environment variables:
> 
> ```
> GITHUB_ID=...
> GITHUB_SECRET=...
> 
> GOOGLE_ID=...
> GOOGLE_SECRET=...
> ```
> 
> Are these correct? Are there any other variables we need to define?

yeah, I've added them to .env.local

**Comment by LKPcode** [comment]
I believe the last commit broke the layout of the other pages.

For example the form viewer:
Screenshot 2024-07-12 at 3 25 52 AM

It probably has to do with the RootLayout or/and some flex properties.
I could fix it myself tomorrow before i merge it.

Its late over here, im going to bed. 😴

**Comment by CR4ZED** [comment]
> I believe the last commit broke the layout of the other pages.
> 
> For example the form viewer: Screenshot 2024-07-12 at 3 25 52 AM
> 
> It probably has to do with the RootLayout or/and some flex properties. I could fix it myself tomorrow before i merge it.
> 
> Its late over here, im going to bed. 😴

if we adjust the margin on the root layout, then we should be fine. Let me check

**Comment by LKPcode** [comment]
They were still a bit wonky, i think because of the margin, converted it to padding and made some small changes to the layouts. Could you check if it ok on your screen as well?

**Pull request merged**
